#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Mar 28 12:58:09 2021

@author: kyle
"""
runtime: python37
entrypoint: gunicorn -w 4 -k uvicorn.workers.UvicornWorker protfolio_construction:port_api
instance_class: F2

